### ISSUE TITLE
Fix or disable TestMetricsAccessible e2e

### ISSUE THREAD

**Issue by damemi** [openshift/cluster-kube-scheduler-operator#322]
This test was added in https://github.com/openshift/cluster-kube-scheduler-operator/pull/191 and regularly flakes, then doesn't. Sometimes it will fail for literally 100's of CI runs before suddenly passing. Other times (like when we tried to fix it by extending the timeout https://github.com/openshift/cluster-kube-scheduler-operator/pull/271) it will instantly pass with no problem.

The failure is due to the retry loop timing out with the metrics not accessible. It regularly blocks PRs and real bug fixes from merging for days. Because of this, and the effort that's already been put into investigating it without any progress, I would like to disable this test until we can dedicate time to finding a real solution.

/kind flake
/kind failing-test

**Comment by damemi** [comment]
/cc @ingvagabund @soltysh 
I'll open a BZ to actually track this

**Comment by smarterclayton** [comment]
The bug was that the CVO profile stuff regressed metrics collection of this new metrics source (the PR to add the metrics landed before profiles, and the CVO profile fix went in 2 days ago and regressed these metrics).  These new metrics are used by the console, so we are debugging the failure that led to the CVO PR merging and introducing this regression.
